test CI validator update

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -16,7 +16,8 @@ jobs:
         os: [windows-latest, macos-latest, ubuntu-latest]
     env:
       DOTNET_NOLOGO: true
-      PERSISTENCE_TEST_YAML_FILES: "src/Persistence.Tests/_TestData/"
+      PERSISTENCE_TEST_YAML_APP_VALID: "src/Persistence.Tests/_TestData/AppsWithYaml/Src"
+      PERSISTENCE_TEST_YAML_FILES_VALID: "src/Persistence.Tests/_TestData/ValidYaml-CI"
 
     steps:
     - uses: actions/checkout@v4
@@ -52,10 +53,16 @@ jobs:
 
     - name: Test - Persistence Test Yaml Files (ubuntu & macos)
       run: |
-        result=$(dotnet bin/Debug/YamlValidator/YamlValidator.dll -validate ${{ env.PERSISTENCE_TEST_YAML_FILES }})
-        echo "$result"
-        if [ "$result" == *"Validation Failed"* ]; then
-          echo "Invalid yaml files found"
+        resultApp=$(dotnet bin/Debug/YamlValidator/YamlValidator.dll validate --path ${{ env.PERSISTENCE_TEST_YAML_APP_VALID }})
+        echo "$resultApp"
+        if [ "$resultApp" == *"Validation Failed"* ]; then
+          echo "Invalid Yaml Files found in ${{ env.PERSISTENCE_TEST_YAML_APP_VALID }}"
+          exit 1
+        fi
+        resultFiles=$(dotnet bin/Debug/YamlValidator/YamlValidator.dll validate --path ${{ env.PERSISTENCE_TEST_YAML_FILES_VALID }})
+        echo "$resultFiles"
+        if [ "$resultFiles" == *"Validation Failed"* ]; then
+          echo "Invalid Yaml Files found in ${{ env.PERSISTENCE_TEST_YAML_FILES_VALID }}"
           exit 1
         fi
       if: ${{ runner.os != 'Windows' }}
